# Generated by Django 5.2.8 on 2025-11-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='track_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
