# Generated by Django 5.2.8 on 2025-11-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_app', '0002_alter_gateway_track_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateway',
            options={'ordering': ('id',), 'verbose_name': 'درخواست پرداخت', 'verbose_name_plural': 'درخواست های پرداخت'},
        ),
    ]
