# Generated by Django 5.2.8 on 2025-11-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_app', '0003_alter_gateway_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(verbose_name='زمان پرداخت')),
                ('amount', models.PositiveIntegerField(verbose_name='مقدار پرداخت شده')),
                ('result', models.PositiveSmallIntegerField(verbose_name='نتیجه پرداخت')),
                ('status', models.PositiveSmallIntegerField(verbose_name='وضعیت')),
                ('ref_number', models.CharField(blank=True, max_length=20, verbose_name='شماره مرجع')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('card_number', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('order_id', models.CharField(blank=True, max_length=20, verbose_name='شماره سفارش')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='پیام')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_gateways', to='gateway_app.gateway', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'نتیجه پرداخت',
                'verbose_name_plural': 'نتایج پرداخت',
                'db_table': 'result_gateway',
                'ordering': ('id',),
            },
        ),
    ]
