# Generated by Django 5.2.8 on 2025-12-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_app', '0004_resultgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='checkout_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='gateway_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
