# Generated by Django 5.2.8 on 2025-11-21 17:52

import django.contrib.postgres.fields
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('core_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('category_name', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیح در مورد دسته بندی')),
                ('description_slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_images', to='core_app.photo', verbose_name='عکس دسته بندی')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='CategoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_body', models.JSONField(default=dict, verbose_name='متن کامنت')),
                ('is_pined', models.BooleanField(default=False, verbose_name='پین شده')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_comments', to='course_app.category', verbose_name='دسته بندی')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='course_app.categorycomment')),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرها',
                'db_table': 'category_comment',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='course_app.categorycomment', verbose_name='کامنت')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_attachments', to='core_app.attachment', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'پیوست کامنت',
                'verbose_name_plural': 'پیوست\u200cهای کامنت',
                'db_table': 'comment_attachment',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('description_slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('project_counter', models.PositiveSmallIntegerField(null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('facilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('course_level', models.CharField(blank=True, max_length=13, null=True)),
                ('time_course', models.CharField(help_text='مدت زمان دوره', max_length=10)),
                ('course_age', models.CharField(blank=True, help_text='بازه سنی دوره', max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_category', to='course_app.category')),
                ('course_image', models.ForeignKey(help_text='حداکثر اندازه عکس 1 مگابایت هست', on_delete=django.db.models.deletion.PROTECT, to='core_app.photo')),
            ],
            options={
                'db_table': 'course',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LessonCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(help_text='نام کلاس')),
                ('progress', models.CharField(choices=[('not_started', 'Not Started'), ('finished', 'Finished'), ('in_progress', 'In Progress')], default='not_started', help_text='وضعیت پیشرفت کلاس', max_length=11)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coach_less_course', to='auth_app.coach', verbose_name='مربی')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_course', to='course_app.course', verbose_name='دوره')),
            ],
            options={
                'db_table': 'lesson_course',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان درس یا سکشن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح سکشن')),
                ('is_last_section', models.BooleanField(default=False, help_text='اگر تیک این مورد خورده باشد یعنی اخرین سکشن برای درس خواهد بود')),
                ('course', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='course_app.course', verbose_name='دوره')),
                ('cover_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.photo', verbose_name='عکس')),
            ],
            options={
                'db_table': 'course_section',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SectionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='عنوان', max_length=50, null=True)),
                ('section', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='section_videos', to='course_app.section')),
                ('video', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='section_videos', to='core_app.video', verbose_name='ویدیو')),
            ],
            options={
                'db_table': 'course_section_video',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StudentAccessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_access', models.BooleanField(default=False)),
                ('section', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='student_section', to='course_app.section')),
                ('student', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='student_access_section', to='auth_app.student')),
            ],
            options={
                'db_table': 'student_access_section',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_status', models.CharField(choices=[('active', 'فعال'), ('cancel', 'انصراف'), ('not_paid', 'پرداخت نکرده')], default='active', max_length=8)),
                ('lesson_course', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_course_enrollment', to='course_app.lessoncourse')),
                ('student', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollment', to='auth_app.student')),
            ],
            options={
                'db_table': 'lesson_course_students',
                'ordering': ('id',),
                'unique_together': {('student', 'lesson_course')},
            },
        ),
        migrations.AddField(
            model_name='lessoncourse',
            name='students',
            field=models.ManyToManyField(related_name='student_lesson_course', through='course_app.StudentEnrollment', to='auth_app.student', verbose_name='دانش جو'),
        ),
    ]
