# Generated by Django 5.2.8 on 2025-11-26 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core_app.photo', verbose_name='عکس'),
        ),
    ]
