# Generated by Django 5.2.8 on 2025-11-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_alter_section_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
        migrations.AddField(
            model_name='lessoncourse',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
