# Generated by Django 5.2.8 on 2025-11-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_remove_course_is_free_lessoncourse_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncourse',
            name='progress',
        ),
    ]
