# Generated by Django 5.2.8 on 2025-11-07 14:44

import auth_app.validators
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('mobile_phone', models.CharField(max_length=15, unique=True, verbose_name='mobile phone')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_image/%Y/%m/%d', validators=[auth_app.validators.validate_upload_image_user], verbose_name='عکس')),
                ('second_mobile_phone', models.CharField(blank=True, max_length=11, null=True, validators=[auth_app.validators.MobileRegexValidator()], verbose_name='شماره تماس دوم')),
                ('nation_code', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[auth_app.validators.NationCodeRegexValidator()], verbose_name='کد ملی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ادرس')),
                ('is_coach', models.BooleanField(default=False, verbose_name='به عنوان مربی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ نولد')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'پسر'), ('Female', 'دختر')], max_length=6, null=True, verbose_name='gender')),
                ('grade', models.CharField(blank=True, choices=[('one', 'اول'), ('two', 'دوم'), ('three', 'سوم'), ('four', 'چهارم'), ('five', 'پنجم'), ('six', 'ششم'), ('seven', 'هفتم'), ('eight', 'هشتم'), ('nine', 'نهم'), ('ten', 'دهم'), ('eleven', 'یازدهم'), ('twelfth', 'دوازدهم'), ('graduate', 'فارغ التحصیل')], max_length=8, null=True, verbose_name='grade')),
                ('school', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام مدرسه')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=40, verbose_name='شهر')),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('coach_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'coach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30, unique=True, verbose_name='استان')),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('student_number', models.CharField(max_length=11)),
                ('referral_code', models.CharField(blank=True, db_index=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
