# Generated by Django 5.2.8 on 2025-11-12 17:08

import auth_app.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth_app.managers.CustomUserManager()),
            ],
        ),
    ]
