# Generated by Django 5.2.8 on 2026-01-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
    ]
