# Generated by Django 5.2.8 on 2025-11-18 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0004_alter_photo_is_active_alter_video_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('duration', models.IntegerField(choices=[(1, '۱ ماهه'), (2, '۲ ماهه'), (3, '۳ ماهه'), (6, '۶ ماهه'), (12, '۱۲ ماهه')], verbose_name='مدت زمان (ماه)')),
                ('original_price', models.BigIntegerField(verbose_name='قیمت اصلی (تومان)')),
                ('discounted_price', models.BigIntegerField(verbose_name='قیمت با تخفیف (تومان)')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core_app.photo', verbose_name='عکس پلن')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
                'db_table': 'subscription_plan',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی شده'), ('canceled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription_app.subscriptionplan', verbose_name='پلن اشتراک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک کاربر',
                'verbose_name_plural': 'اشتراک\u200cهای کاربران',
                'db_table': 'user_subscription',
                'ordering': ('id',),
            },
        ),
    ]
