# Generated by Django 5.2.8 on 2025-11-21 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام طرح قسطی')),
                ('plan_type', models.CharField(choices=[('fixed', 'قسط ثابت'), ('variable', 'قسط متغیر')], default='fixed', max_length=20, verbose_name='نوع طرح')),
                ('number_of_installments', models.IntegerField(db_default=1, default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد اقساط')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نرخ سود (درصد)')),
            ],
            options={
                'verbose_name': 'طرح قسطی',
                'verbose_name_plural': 'طرح\u200cهای قسطی',
                'db_table': 'installment_plan',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InstallmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.IntegerField(verbose_name='شماره قسط')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ قسط (تومان)')),
                ('due_days', models.IntegerField(verbose_name='تعداد روز تا سررسید')),
                ('installment_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='subscription_app.installmentplan', verbose_name='طرح قسطی')),
            ],
            options={
                'verbose_name': 'گزینه قسط',
                'verbose_name_plural': 'گزینه\u200cهای قسط',
                'db_table': 'installment_option',
                'ordering': ('id',),
                'unique_together': {('installment_plan', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_installment', models.BooleanField(default=False, verbose_name='امکان خرید قسطی')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('duration', models.IntegerField(choices=[(1, '۱ ماهه'), (2, '۲ ماهه'), (3, '۳ ماهه'), (6, '۶ ماهه'), (12, '۱۲ ماهه')], verbose_name='مدت زمان (ماه)')),
                ('original_price', models.BigIntegerField(verbose_name='قیمت اصلی (تومان)')),
                ('discounted_price', models.BigIntegerField(verbose_name='قیمت با تخفیف (تومان)')),
                ('min_installment_months', models.IntegerField(db_default=0, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل مدت برای قسطی (ماه)')),
                ('max_installments', models.IntegerField(db_default=0, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر تعداد اقساط مجاز')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core_app.photo', verbose_name='عکس پلن')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
                'db_table': 'subscription_plan',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='subscription_plan',
            field=models.ForeignKey(limit_choices_to={'has_installment': True}, on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='subscription_app.subscriptionplan', verbose_name='پلن اشتراک'),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی شده'), ('canceled', 'لغو شده'), ('reserve', 'رزو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription_app.subscriptionplan', verbose_name='پلن اشتراک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک کاربر',
                'verbose_name_plural': 'اشتراک\u200cهای کاربران',
                'db_table': 'user_subscription',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.IntegerField(verbose_name='شماره قسط')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ قسط (تومان)')),
                ('due_date', models.DateTimeField(verbose_name='تاریخ سررسید')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('overdue', 'معوقه'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش')),
                ('installment_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription_app.installmentoption', verbose_name='گزینه قسط')),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='subscription_app.usersubscription', verbose_name='اشتراک کاربر')),
            ],
            options={
                'verbose_name': 'قسط کاربر',
                'verbose_name_plural': 'قسط\u200cهای کاربران',
                'db_table': 'user_installment',
                'ordering': ('id',),
            },
        ),
    ]
