# Generated by Django 5.2.8 on 2025-11-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_installment',
            field=models.BooleanField(default=False, verbose_name='امکان خرید قسطی'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_installments',
            field=models.IntegerField(default=12, verbose_name='حداکثر تعداد اقساط مجاز'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='min_installment_months',
            field=models.IntegerField(default=3, verbose_name='حداقل مدت برای قسطی (ماه)'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی شده'), ('canceled', 'لغو شده'), ('reserve', 'رزو شده')], default='active', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام طرح قسطی')),
                ('plan_type', models.CharField(choices=[('fixed', 'قسط ثابت'), ('variable', 'قسط متغیر')], default='fixed', max_length=20, verbose_name='نوع طرح')),
                ('number_of_installments', models.IntegerField(verbose_name='تعداد اقساط')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ سود (درصد)')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='subscription_app.subscriptionplan', verbose_name='پلن اشتراک')),
            ],
            options={
                'verbose_name': 'طرح قسطی',
                'verbose_name_plural': 'طرح\u200cهای قسطی',
                'db_table': 'installment_plan',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InstallmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.IntegerField(verbose_name='شماره قسط')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ قسط (تومان)')),
                ('due_days', models.IntegerField(verbose_name='تعداد روز تا سررسید')),
                ('installment_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='subscription_app.installmentplan', verbose_name='طرح قسطی')),
            ],
            options={
                'verbose_name': 'گزینه قسط',
                'verbose_name_plural': 'گزینه\u200cهای قسط',
                'db_table': 'installment_option',
                'ordering': ('id',),
                'unique_together': {('installment_plan', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='UserInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.IntegerField(verbose_name='شماره قسط')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ قسط (تومان)')),
                ('due_date', models.DateTimeField(verbose_name='تاریخ سررسید')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('overdue', 'معوقه'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه تراکنش')),
                ('installment_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription_app.installmentoption', verbose_name='گزینه قسط')),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='subscription_app.usersubscription', verbose_name='اشتراک کاربر')),
            ],
            options={
                'verbose_name': 'قسط کاربر',
                'verbose_name_plural': 'قسط\u200cهای کاربران',
                'db_table': 'user_installment',
                'ordering': ('id',),
            },
        ),
    ]
