# Generated by Django 5.2.8 on 2025-11-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0002_subscriptionplan_has_installment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_installments',
            field=models.IntegerField(default=0, verbose_name='حداکثر تعداد اقساط مجاز'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='min_installment_months',
            field=models.IntegerField(default=0, verbose_name='حداقل مدت برای قسطی (ماه)'),
        ),
    ]
