# Generated by Django 5.2.8 on 2025-11-19 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0003_alter_subscriptionplan_max_installments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_installments',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر تعداد اقساط مجاز'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='min_installment_months',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل مدت برای قسطی (ماه)'),
        ),
    ]
