# Generated by Django 5.2.8 on 2025-11-19 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0008_alter_subscriptionplan_max_installments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نرخ سود (درصد)'),
        ),
    ]
