# Generated by Django 5.2.8 on 2025-11-19 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0009_alter_installmentplan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='number_of_installments',
            field=models.IntegerField(db_default=1, default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد اقساط'),
        ),
    ]
