# Generated by Django 5.2.8 on 2025-11-19 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0010_alter_installmentplan_number_of_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentplan',
            name='subscription_plan',
            field=models.ForeignKey(limit_choices_to={'has_installment': True}, on_delete=django.db.models.deletion.PROTECT, related_name='installment_plans', to='subscription_app.subscriptionplan', verbose_name='پلن اشتراک'),
        ),
    ]
