# Generated by Django 5.2.8 on 2025-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0011_alter_installmentplan_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
