# Generated by Django 5.2.8 on 2025-11-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0002_alter_challengesubmission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('JA', 'Java'), ('C#', 'C#'), ('JS', 'JavaScript'), ('C++', 'C++')], max_length=50, verbose_name='زبان برنامه\u200cنویسی'),
        ),
    ]
