# Generated by Django 5.2.8 on 2025-11-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0004_remove_challengesubmission_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesubmission',
            name='score',
            field=models.FloatField(default=0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='challengesubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('accepted', 'پذیرفته شده'), ('wrong_answer', 'پاسخ اشتباه'), ('time_limit_exceeded', 'محدودیت زمان'), ('memory_limit_exceeded', 'محدودیت حافظه'), ('runtime_error', 'خطای زمان اجرا'), ('compilation_error', 'خطای کامپایل'), ('solved', 'حل شده')], default='pending', max_length=30, verbose_name='وضعیت'),
        ),
    ]
