# Generated by Django 5.2.8 on 2025-11-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0005_challengesubmission_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCase',
        ),
    ]
