# Generated by Django 5.2.8 on 2025-11-23 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0007_userchallengescore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchallengescore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='score_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
