# Generated by Django 5.2.8 on 2025-11-21 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'wmv'])], verbose_name='فایل ویدیو')),
                ('video_url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='لینک ویدیو')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان')),
                ('file_format', models.CharField(blank=True, max_length=10, verbose_name='فرمت فایل')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
                'db_table': 'videos',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mp3', 'wav', 'ogg', 'm4a', 'flac', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'zip', 'rar', '7z', 'tar', 'gz'))], verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('image', 'عکس'), ('video', 'ویدیو'), ('audio', 'صدا'), ('document', 'سند'), ('archive', 'آرشیو'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع فایل')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم فایل (بایت)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع MIME')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض (پیکسل)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع (پیکسل)')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='مدت زمان (ثانیه)')),
                ('upload_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیوست',
                'verbose_name_plural': 'پیوست\u200cها',
                'db_table': 'attachment',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(height_field='height', upload_to='photos/%Y/%m/%d/', verbose_name='تصویر', width_field='width')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('file_format', models.CharField(blank=True, max_length=10, verbose_name='فرمت فایل')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس\u200cها',
                'ordering': ('-id',),
            },
        ),
    ]
