# Generated by Django 5.2.8 on 2025-11-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(height_field='height', upload_to='photos/%Y/%m/%d/', verbose_name='تصویر', width_field='width')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('file_format', models.CharField(blank=True, max_length=10, verbose_name='فرمت فایل')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس\u200cها',
                'ordering': ('-id',),
            },
        ),
    ]
