# Generated by Django 5.2.8 on 2025-11-12 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'wmv'])], verbose_name='فایل ویدیو')),
                ('video_url', models.URLField(blank=True, max_length=2048, null=True, verbose_name='لینک ویدیو')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان')),
                ('file_format', models.CharField(blank=True, max_length=10, verbose_name='فرمت فایل')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
                'db_table': 'videos',
                'ordering': ('-id',),
            },
        ),
    ]
