# Generated by Django 5.2.8 on 2025-11-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_photo_upload_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
