# Generated by Django 5.2.8 on 2025-11-20 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_photo_is_active_alter_video_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg', 'mp4', 'avi', 'mov', 'wmv', 'flv', 'webm', 'mp3', 'wav', 'ogg', 'm4a', 'flac', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'zip', 'rar', '7z', 'tar', 'gz'))], verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('image', 'عکس'), ('video', 'ویدیو'), ('audio', 'صدا'), ('document', 'سند'), ('archive', 'آرشیو'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع فایل')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم فایل (بایت)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع MIME')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='عرض (پیکسل)')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ارتفاع (پیکسل)')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='مدت زمان (ثانیه)')),
            ],
            options={
                'verbose_name': 'پیوست',
                'verbose_name_plural': 'پیوست\u200cها',
                'db_table': 'attachment',
                'ordering': ('id',),
            },
        ),
    ]
