# Generated by Django 5.2.8 on 2025-11-20 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_app', '0004_alter_photo_is_active_alter_video_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='عنوان چالش')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='شرح چالش')),
                ('language', models.CharField(choices=[('PY', 'Python'), ('JA', 'Java'), ('html', 'HTML'), ('C#', 'C#'), ('js', 'JavaScript'), ('c++', 'C++')], max_length=50, verbose_name='زبان برنامه\u200cنویسی')),
                ('level', models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'سخت'), ('expert', 'حرفه\u200cای')], max_length=10, verbose_name='سطح')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('success_percent', models.FloatField(default=0, verbose_name='درصد موفقیت')),
                ('total_submissions', models.IntegerField(default=0, verbose_name='تعداد کل ارسال\u200cها')),
                ('successful_submissions', models.IntegerField(default=0, verbose_name='تعداد ارسال\u200cهای موفق')),
                ('avg_completion_time', models.FloatField(default=0, verbose_name='میانگین زمان حل (ثانیه)')),
                ('time_limit', models.IntegerField(default=2000, verbose_name='محدودیت زمان (میلی\u200cثانیه)')),
                ('memory_limit', models.IntegerField(default=256, verbose_name='محدودیت حافظه (مگابایت)')),
                ('points', models.IntegerField(default=10, verbose_name='امتیاز')),
                ('coins', models.IntegerField(default=0, verbose_name='سکه پاداش')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='core_app.photo', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'چالش',
                'verbose_name_plural': 'چالش\u200cها',
                'db_table': 'challenge',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.TextField(verbose_name='کد ارسالی')),
                ('language', models.CharField(max_length=50, verbose_name='زبان برنامه\u200cنویسی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('accepted', 'پذیرفته شده'), ('wrong_answer', 'پاسخ اشتباه'), ('time_limit_exceeded', 'محدودیت زمان'), ('memory_limit_exceeded', 'محدودیت حافظه'), ('runtime_error', 'خطای زمان اجرا'), ('compilation_error', 'خطای کامپایل')], default='pending', max_length=30, verbose_name='وضعیت')),
                ('execution_time', models.IntegerField(blank=True, null=True, verbose_name='زمان اجرا (میلی\u200cثانیه)')),
                ('memory_used', models.IntegerField(blank=True, null=True, verbose_name='حافظه استفاده شده (کیلوبایت)')),
                ('score', models.FloatField(default=0, verbose_name='امتیاز')),
                ('test_results', models.JSONField(blank=True, default=dict, verbose_name='نتایج تست\u200cها')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='challenge_app.challenge', verbose_name='چالش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenge_submissions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ارسال چالش',
                'verbose_name_plural': 'ارسال\u200cهای چالش',
                'db_table': 'challenge_submission',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_data', models.CharField(max_length=500, verbose_name='ورودی')),
                ('expected_output', models.CharField(max_length=500, verbose_name='خروجی مورد انتظار')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='challenge_app.challenge', verbose_name='چالش')),
            ],
            options={
                'verbose_name': 'تست\u200cکیس',
                'verbose_name_plural': 'تست\u200cکیس\u200cها',
                'db_table': 'test_case',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('best_score', models.FloatField(default=0, verbose_name='بهترین امتیاز')),
                ('attempts_count', models.IntegerField(default=0, verbose_name='تعداد تلاش\u200cها')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('best_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='challenge_app.challengesubmission', verbose_name='بهترین ارسال')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_progress', to='challenge_app.challenge', verbose_name='چالش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenge_progress', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیشرفت کاربر در چالش',
                'verbose_name_plural': 'پیشرفت\u200cهای کاربران در چالش\u200cها',
                'db_table': 'user_challenge_progress',
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
