# Generated by Django 5.2.8 on 2025-11-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengesubmission',
            name='code',
            field=models.FileField(upload_to='', verbose_name='کد ارسالی'),
        ),
    ]
