# Generated by Django 5.2.8 on 2025-11-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ('id',), 'verbose_name': 'چالش', 'verbose_name_plural': 'چالش\u200cها'},
        ),
    ]
