# Generated by Django 5.2.8 on 2025-11-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0002_alter_challenge_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='slug',
        ),
    ]
