# Generated by Django 5.2.8 on 2025-11-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0003_remove_challenge_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='order',
            field=models.IntegerField(db_default=0, default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
