# Generated by Django 5.2.8 on 2025-11-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0003_alter_challenge_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengesubmission',
            name='code',
        ),
        migrations.RemoveField(
            model_name='challengesubmission',
            name='execution_time',
        ),
        migrations.RemoveField(
            model_name='challengesubmission',
            name='language',
        ),
        migrations.RemoveField(
            model_name='challengesubmission',
            name='memory_used',
        ),
        migrations.RemoveField(
            model_name='challengesubmission',
            name='score',
        ),
        migrations.RemoveField(
            model_name='challengesubmission',
            name='test_results',
        ),
    ]
