# Generated by Django 5.2.8 on 2025-11-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0004_alter_challenge_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('JA', 'Java'), ('HTML', 'HTML'), ('C#', 'C#'), ('JS', 'JavaScript'), ('C++', 'C++')], max_length=50, verbose_name='زبان برنامه\u200cنویسی'),
        ),
    ]
