# Generated by Django 5.2.8 on 2025-11-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0005_alter_challenge_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.JSONField(verbose_name='شرح چالش'),
        ),
    ]
