# Generated by Django 5.2.8 on 2025-11-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_app', '0008_alter_userchallengescore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
