# Generated by Django 5.2.8 on 2025-11-21 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.JSONField(default=dict, verbose_name='متن سوال')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'چند گزینه\u200cای'), ('code', 'کد')], max_length=20, verbose_name='نوع سوال')),
                ('score', models.PositiveIntegerField(default=1, verbose_name='نمره سوال')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('explanation', models.JSONField(blank=True, null=True, verbose_name='راهنمایی پاسخ')),
                ('answer_the_question', models.JSONField(blank=True, default=dict, null=True, verbose_name='پاسخ سوال')),
            ],
            options={
                'verbose_name': 'سوال آزمون',
                'verbose_name_plural': 'سوالات آزمون',
                'db_table': 'exam_question',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice_text', models.CharField(max_length=500, verbose_name='متن گزینه')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='exam_app.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'گزینه سوال',
                'verbose_name_plural': 'گزینه\u200cهای سوال',
                'db_table': 'exam_choice',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SectionExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آزمون')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات آزمون')),
                ('exam_type', models.CharField(choices=[('quiz', 'کوییز'), ('midterm', 'کد')], default='quiz', max_length=20, verbose_name='نوع آزمون')),
                ('total_score', models.PositiveIntegerField(default=100, verbose_name='نمره کل')),
                ('passing_score', models.PositiveIntegerField(default=50, verbose_name='نمره قبولی')),
                ('section', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='section_exams', to='course_app.section', verbose_name='سکشن')),
            ],
            options={
                'verbose_name': 'آزمون سکشن',
                'verbose_name_plural': 'آزمون\u200cهای سکشن',
                'db_table': 'section_exam',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='exam_app.sectionexam', verbose_name='آزمون'),
        ),
        migrations.CreateModel(
            name='StudentExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('total_score', models.FloatField(default=0, verbose_name='نمره کل')),
                ('obtained_score', models.FloatField(default=0, verbose_name='نمره کسب شده')),
                ('is_passed', models.BooleanField(default=False, verbose_name='قبول شده')),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('graded', 'تصحیح شده')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='exam_app.sectionexam', verbose_name='آزمون')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_attempts', to='auth_app.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'شرکت در آزمون',
                'verbose_name_plural': 'شرکت\u200cهای در آزمون',
                'db_table': 'student_exam_attempt',
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='ExamGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.FloatField(verbose_name='نمره کل')),
                ('obtained_score', models.FloatField(verbose_name='نمره کسب شده')),
                ('grade', models.CharField(max_length=5, verbose_name='نمره')),
                ('feedback', models.TextField(blank=True, verbose_name='نظر کلی')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_gradings', to='auth_app.student', verbose_name='دانش\u200cآموز')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradings', to='exam_app.sectionexam', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'تصحیح آزمون',
                'verbose_name_plural': 'تصحیح\u200cهای آزمون',
                'db_table': 'exam_grading',
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(default=0, verbose_name='نمره کسب شده')),
                ('teacher_feedback', models.TextField(blank=True, verbose_name='نظر مربی')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تصحیح')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='صحیح است')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='exam_app.question', verbose_name='سوال')),
                ('selected_choices', models.ManyToManyField(blank=True, to='exam_app.choice', verbose_name='گزینه\u200cهای انتخاب شده')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='auth_app.student')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='exam_app.studentexamattempt', verbose_name='شرکت در آزمون')),
            ],
            options={
                'verbose_name': 'پاسخ دانش\u200cآموز',
                'verbose_name_plural': 'پاسخ\u200cهای دانش\u200cآموزان',
                'db_table': 'student_exam_answer',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
