# Generated by Django 5.2.8 on 2025-11-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_alter_studentexamattempt_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentexamattempt',
            options={'verbose_name': 'شرکت در آزمون', 'verbose_name_plural': 'ازمون های شرکت کرده'},
        ),
        migrations.AlterField(
            model_name='studentexamattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'در حال انجام'), ('done', 'ازمون تمام شده')], default='in_progress', max_length=20, verbose_name='وضعیت'),
        ),
    ]
