# Generated by Django 5.2.8 on 2025-11-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_alter_studentexamattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='صحیح است'),
        ),
    ]
