# Generated by Django 5.2.8 on 2025-11-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_alter_studentanswer_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamattempt',
            name='total_score',
        ),
    ]
