# Generated by Django 5.2.8 on 2025-11-07 14:44

import course_app.models
import course_app.validators
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('category_name', models.CharField(db_index=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/%Y/%m/%d')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('description_slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('is_publish', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('unique_code', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='certificates/qr_codes/%Y/%m/%d/')),
                ('final_pdf', models.FileField(blank=True, null=True, upload_to='certificates/pdf/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'course_certificate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('template_image', models.ImageField(help_text='حداکثر اندازه سایز تمپلیت ۲ مگابایت باشد', upload_to='certificate_template/%Y/%m/%d', validators=[course_app.validators.max_upload_image_validator])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'certificate_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('course_name', models.CharField(db_index=True, max_length=100)),
                ('course_description', models.TextField()),
                ('description_slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('course_image', models.ImageField(blank=True, help_text='حداکثر اندازه عکس 1 مگابایت هست', upload_to='course_image/%Y/%m/%d', validators=[course_app.validators.max_upload_image_validator])),
                ('is_publish', models.BooleanField(default=True)),
                ('project_counter', models.PositiveSmallIntegerField(null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('facilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('course_level', models.CharField(blank=True, max_length=13, null=True)),
                ('time_course', models.CharField(blank=True, help_text='مدت زمان دوره', max_length=10)),
                ('course_age', models.CharField(blank=True, help_text='بازه سنی دوره', max_length=30)),
                ('order_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'ordering': ('-id',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('class_name', models.CharField(help_text='نام کلاس')),
                ('is_active', models.BooleanField(default=True)),
                ('progress', models.CharField(choices=[('not_started', 'Not Started'), ('finished', 'Finished'), ('in_progress', 'In Progress')], default='not_started', help_text='وضعیت پیشرفت کلاس', max_length=11, null=True)),
                ('for_mobile', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lesson_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(null=True, upload_to='section_cover_image/%Y/%m/%d', validators=[course_app.validators.max_upload_image_validator])),
                ('is_publish', models.BooleanField(default=True)),
                ('is_last_section', models.BooleanField(default=False, help_text='اگر تیک این مورد خورده باشد یعنی اخرین سکشن برای درس خواهد بود')),
            ],
            options={
                'db_table': 'course_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('title', models.CharField(help_text='عنوان', max_length=100, null=True)),
                ('zip_file', models.FileField(blank=True, upload_to='section_file/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])])),
                ('file_type', models.CharField(choices=[('main', 'تمرین اصلی'), ('more', 'تمرین اضافی')], max_length=9, null=True)),
                ('answer', models.FileField(blank=True, null=True, upload_to='answer/section_file/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])])),
                ('is_publish', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'course_section_file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('title', models.CharField(help_text='عنوان', max_length=50, null=True)),
                ('video', models.FileField(blank=True, upload_to='section_video/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_publish', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'course_section_video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SendSectionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('send_file_status', models.CharField(blank=True, choices=[('rejected', 'رد شده'), ('accept_to_wait', 'در انتظا تایید'), ('accepted', 'تایید شده')], default='accept_to_wait', help_text='وضعیت فایل ارسالی', max_length=14, null=True)),
                ('zip_file', models.FileField(help_text='فایل ارسالی', upload_to=course_app.models.SendSectionFile.student_send_section_file)),
                ('comment_student', models.TextField(help_text='توضیحی در مورد تمرین ارسالی', null=True)),
                ('comment_teacher', models.CharField(blank=True, help_text='توضیح مربی در مورد فایل ارسال شده دانشجو', max_length=255, null=True)),
                ('score', models.FloatField(blank=True, help_text='نمره تکلیف ارسالی', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'db_table': 'send_file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAccessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('is_access', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student_access_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('student_status', models.CharField(blank=True, choices=[('active', 'فعال'), ('cancel', 'انصراف'), ('not_paid', 'پرداخت نکرده')], default='active', max_length=8)),
            ],
            options={
                'db_table': 'lesson_course_students',
                'managed': False,
            },
        ),
    ]
