# Generated by Django 5.2.8 on 2025-11-06 19:55

import course_app.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('category_name', models.CharField(db_index=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/%Y/%m/%d')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('description_slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('is_publish', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('is_deleted', models.BooleanField(editable=False, null=True)),
                ('course_name', models.CharField(db_index=True, max_length=100)),
                ('course_description', models.TextField()),
                ('description_slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('course_image', models.ImageField(blank=True, help_text='حداکثر اندازه عکس 1 مگابایت هست', upload_to='course_image/%Y/%m/%d', validators=[course_app.validators.max_upload_image_validator])),
                ('is_publish', models.BooleanField(default=True)),
                ('project_counter', models.PositiveSmallIntegerField(null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('facilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None)),
                ('course_level', models.CharField(blank=True, max_length=13, null=True)),
                ('time_course', models.CharField(blank=True, help_text='مدت زمان دوره', max_length=10)),
                ('course_age', models.CharField(blank=True, help_text='بازه سنی دوره', max_length=30)),
                ('order_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'ordering': ('-id',),
                'managed': False,
            },
        ),
    ]
