# Generated by Django 5.2.8 on 2025-11-12 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_video'),
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='lessoncourse',
            name='for_mobile',
        ),
        migrations.RemoveField(
            model_name='sectionvideo',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ForeignKey(help_text='حداکثر اندازه عکس 1 مگابایت هست', on_delete=django.db.models.deletion.PROTECT, to='core_app.photo'),
        ),
        migrations.AlterField(
            model_name='sectionvideo',
            name='video',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='section_videos', to='core_app.video', verbose_name='ویدیو'),
        ),
    ]
