# Generated by Django 5.2.8 on 2025-11-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_alter_studentenrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
