# Generated by Django 5.2.8 on 2025-11-18 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_studentenrollment_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('comment_body', models.TextField(verbose_name='متن کامنت')),
                ('is_publish', models.BooleanField(default=True, verbose_name='انتشار')),
                ('is_pined', models.BooleanField(default=False, verbose_name='پین شده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_comments', to='course_app.category', verbose_name='دسته بندی')),
                ('user', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'db_table': 'category_comment',
                'ordering': ('-id',),
            },
        ),
    ]
