# Generated by Django 5.2.8 on 2025-11-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_categorycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorycomment',
            name='comment_body',
            field=models.JSONField(default=dict, verbose_name='متن کامنت'),
        ),
    ]
