# Generated by Django 5.2.8 on 2025-11-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_remove_lessoncourse_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncourse',
            name='student_number',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجویان کلاس'),
        ),
    ]
