# Generated by Django 5.2.8 on 2025-11-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_alter_categorycomment_comment_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycomment',
            name='is_publish',
        ),
    ]
