# Generated by Django 5.2.8 on 2025-11-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_remove_categorycomment_is_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycomment',
            options={'ordering': ('id',)},
        ),
    ]
