# Generated by Django 5.2.8 on 2025-11-20 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_attachment'),
        ('course_app', '0007_alter_categorycomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorycomment',
            options={'ordering': ('id',), 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرها'},
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='course_app.categorycomment', verbose_name='کامنت')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_attachments', to='core_app.attachment', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'پیوست کامنت',
                'verbose_name_plural': 'پیوست\u200cهای کامنت',
                'db_table': 'comment_attachment',
            },
        ),
        migrations.AddField(
            model_name='categorycomment',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachment_comments', to='course_app.commentattachment', verbose_name='فایل'),
        ),
    ]
