# Generated by Django 5.2.8 on 2025-11-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_alter_categorycomment_options_commentattachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorycomment',
            name='attachment',
        ),
    ]
