# Generated by Django 5.2.8 on 2025-11-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_remove_categorycomment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentattachment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='course_app.categorycomment', verbose_name='کامنت'),
        ),
    ]
