# Generated by Django 5.2.8 on 2025-11-21 17:52

import apps.auth_app.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_phone', models.CharField(max_length=15, unique=True, verbose_name='mobile phone')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('nation_code', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[
                    apps.auth_app.validators.NationCodeRegexValidator()], verbose_name='کد ملی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ادرس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ نولد')),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('is_coach', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'پسر'), ('Female', 'دختر')], max_length=6, null=True, verbose_name='gender')),
                ('school', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام مدرسه')),
            ],
            options={
                'db_table': 'users',
                'ordering': ('id',),
            },
            managers=[
                ('objects', apps.auth_app.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.CharField(db_index=True, max_length=40, verbose_name='شهر')),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach_number', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('state_name', models.CharField(max_length=30, unique=True, verbose_name='استان')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_number', models.CharField(max_length=11)),
                ('referral_code', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
