# Generated by Django 5.2.8 on 2025-11-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-id',), 'verbose_name': 'سوال آزمون', 'verbose_name_plural': 'سوالات آزمون'},
        ),
        migrations.AlterField(
            model_name='question',
            name='display_order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش'),
        ),
    ]
