# Generated by Django 5.2.8 on 2025-11-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'پذیرفته شده'), ('reject', 'رد شده')], max_length=10, null=True),
        ),
    ]
