# Generated by Django 5.2.8 on 2025-11-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_alter_question_options_alter_question_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'گزینه سوال', 'verbose_name_plural': 'گزینه\u200cهای سوال'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',), 'verbose_name': 'سوال آزمون', 'verbose_name_plural': 'سوالات آزمون'},
        ),
        migrations.AlterModelOptions(
            name='sectionexam',
            options={'ordering': ('-id',), 'verbose_name': 'آزمون سکشن', 'verbose_name_plural': 'آزمون\u200cهای سکشن'},
        ),
    ]
