# Generated by Django 5.2.8 on 2025-11-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_studentanswer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'در حال انجام'), ('graded', 'تصحیح شده'), ('done', 'ازموت تمام شده')], default='in_progress', max_length=20, verbose_name='وضعیت'),
        ),
    ]
