# Generated by Django 5.2.8 on 2025-11-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('id',), 'verbose_name': 'گزینه سوال', 'verbose_name_plural': 'گزینه\u200cهای سوال'},
        ),
        migrations.AlterModelOptions(
            name='sectionexam',
            options={'ordering': ('id',), 'verbose_name': 'آزمون سکشن', 'verbose_name_plural': 'آزمون\u200cهای سکشن'},
        ),
        migrations.AddField(
            model_name='choice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
