# Generated by Django 5.2.8 on 2025-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_alter_choice_options_alter_sectionexam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='متن گزینه'),
        ),
    ]
