# Generated by Django 5.2.8 on 2025-11-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_choice_choice_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='display_order',
        ),
    ]
