# Generated by Django 5.2.8 on 2025-11-13 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_managers'),
        ('exam_app', '0006_remove_choice_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examgrading',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradings', to='exam_app.sectionexam', verbose_name='آزمون'),
        ),
        migrations.AlterField(
            model_name='examgrading',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_gradings', to='auth_app.student', verbose_name='دانش\u200cآموز'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='exam_app.studentexamattempt', verbose_name='شرکت در آزمون'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='exam_app.question', verbose_name='سوال'),
        ),
    ]
