# Generated by Django 5.2.8 on 2025-11-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_remove_studentexamattempt_total_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamattempt',
            unique_together=set(),
        ),
    ]
