# Generated by Django 5.2.8 on 2025-11-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_alter_examgrading_exam_alter_examgrading_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
