# Generated by Django 5.2.8 on 2025-11-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0009_remove_studentanswer_graded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='examgrading',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
