# Generated by Django 5.2.8 on 2025-11-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0010_examgrading_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examgrading',
            name='percentage',
        ),
    ]
