# Generated by Django 5.2.8 on 2025-11-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0011_remove_examgrading_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.JSONField(verbose_name='متن سوال'),
        ),
        migrations.AlterField(
            model_name='sectionexam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
