# Generated by Django 5.2.8 on 2025-11-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_city_is_active_state_is_active'),
        ('exam_app', '0012_alter_question_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='auth_app.student'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.JSONField(default=dict, verbose_name='متن سوال'),
        ),
    ]
