# Generated by Django 5.2.8 on 2025-11-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0013_studentanswer_student_alter_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionexam',
            name='time_limit',
        ),
    ]
