# Generated by Django 5.2.8 on 2025-11-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0014_remove_sectionexam_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='راهنمایی پاسخ'),
        ),
    ]
