# Generated by Django 5.2.8 on 2025-11-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0015_alter_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_the_question',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='پاسخ سوال'),
        ),
    ]
