# Generated by Django 5.2.8 on 2025-11-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0016_question_answer_the_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.JSONField(blank=True, null=True, verbose_name='راهنمایی پاسخ'),
        ),
    ]
