# Generated by Django 5.2.8 on 2025-11-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0017_alter_question_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'چند گزینه\u200cای'), ('code', 'کد')], max_length=20, verbose_name='نوع سوال'),
        ),
    ]
