# Generated by Django 5.2.8 on 2026-01-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='discounted_price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت با تخفیف (تومان)'),
        ),
    ]
